sudo: required
dist: xenial
language: go
go: "1.12"

branches:
  only:
  - master
  - /^v[0-9]/

services:
- docker

jobs:
  include:
  - stage: Tests
    name: "minishift"
    env: CPLATFORM=minishift TARGET=functests V=5 CI_CONFIG_FEATURE_GATES=DataVolumes,LiveMigration,CPUManager CI_CONFIG_ADMISSION_WEBHOOK=1

  - stage: Build and Deploy
    name: Build and Deploy to GitHub
    if: tag IS present
    before_script: skip
    script: make release "VERSION=$TRAVIS_TAG"
    deploy:
      provider: releases
      api_key: "$GITHUB_TOKEN"
      skip_cleanup: true
      overwrite: true
      file_glob: true
      file:
      - _out/*
      name: $TRAVIS_TAG
      on:
        tags: true
        branch: master
        repo: $TRAVIS_REPO_SLUG

addons:
  apt:
    packages:
      - netcat
      - openssl

cache:
  directories:
  - cache
  - "~/.minishift/cache"

before_script:
## FIXME Workaround for https://github.com/kubernetes/kubernetes/issues/61058
### And https://github.com/LiliC/travis-minikube/blob/e0f26f7b388057f51a0e2558afd5f990e07b6c49/.travis.yml#L11
- sudo mount --make-rshared /

## FIXME - kubevirt v0.28.0 uses functionality which os-3.11.0 doesn't support
## we need to migrate tests to use OKD/OCP - 4.*
## For now kubevirt version is hardcoded to v0.27.0
#- bash -x ci/ci/extra/get-kubevirt-releases

- bash -x ci/prepare-host $CPLATFORM
- bash -x ci/prepare-host virtctl
- bash -x ci/start-cluster $CPLATFORM $CVER
- bash -x hack/ci/deploy-kubevirt $CPLATFORM

- bash -x hack/env/build-validator.sh
- bash -x hack/env/install-validator.sh

script:
- bash -x test.sh
- bash -x hack/env/upgrade-and-test.sh old-to-builtin
- bash -x hack/env/upgrade-and-test.sh builtin-to-new
