apiVersion: v1
kind: Template
metadata:
  name: fedora-desktop-small-with-rules
  annotations:
    openshift.io/display-name: "Fedora 23+ VM"
    description: >-
      This template can be used to create a VM suitable for
      Fedora 23 and newer.
      The template assumes that a PVC is available which is providing the
      necessary Fedora disk image.

      Recommended disk image (needs to be converted to raw)
      https://download.fedoraproject.org/pub/fedora/linux/releases/28/Cloud/x86_64/images/Fedora-Cloud-Base-28-1.1.x86_64.qcow2
    tags: "kubevirt,virtualmachine,fedora,rhel"

    iconClass: "icon-fedora"
    openshift.io/provider-display-name: "KubeVirt"
    openshift.io/documentation-url: "https://github.com/kubevirt/common-templates"
    openshift.io/support-url: "https://github.com/kubevirt/common-templates/issues"
    template.openshift.io/bindable: "false"

    template.kubevirt.io/version: v1alpha1
    defaults.template.kubevirt.io/disk: rootdisk
    template.kubevirt.io/editable: |
      /objects[0].spec.template.spec.domain.cpu.sockets
      /objects[0].spec.template.spec.domain.cpu.cores
      /objects[0].spec.template.spec.domain.cpu.threads
      /objects[0].spec.template.spec.domain.resources.requests.memory
      /objects[0].spec.template.spec.domain.devices.disks
      /objects[0].spec.template.spec.volumes
      /objects[0].spec.template.spec.networks

    name.os.template.kubevirt.io/fedora26: Fedora 26
    name.os.template.kubevirt.io/fedora27: Fedora 27
    name.os.template.kubevirt.io/fedora28: Fedora 28
    validations: |
      [
        {
          "name": "EnoughMemory",
          "path": "jsonpath::.spec.domain.resources.requests.memory",
          "message": "Memory size not within range",
          "rule": "integer",
          "min": 67108864,
          "max": 536870912
        },
        {
          "name": "LimitCores",
          "path": "jsonpath::.spec.domain.cpu.cores",
          "message": "Core amount not within range",
          "rule": "integer",
          "min": 1,
          "max": 4
        },
        {
          "name": "SupportedChipset",
          "path": "jsonpath::.spec.domain.machine.type",
          "message": "Machine type is a supported value",
          "rule": "enum",
          "values": ["q35"]
        }
      ]
  labels:
    os.template.kubevirt.io/fedora26: "true"
    os.template.kubevirt.io/fedora27: "true"
    os.template.kubevirt.io/fedora28: "true"
    workload.template.kubevirt.io/generic: "true"
    flavor.template.kubevirt.io/small: "true"
    template.kubevirt.io/type: "base"

objects:
- apiVersion: kubevirt.io/v1alpha3
  kind: VirtualMachine
  metadata:
    name: ${NAME}
    labels:
      vm.kubevirt.io/template: fedora-desktop-small
      app: ${NAME}
  spec:
    running: false
    template:
      spec:
        domain:

          cpu:
            sockets: 1
            cores: 1
            threads: 1
          resources:
            requests:
              memory: 2G
          devices:
            rng: {}
            disks:
            - disk:
                bus: virtio
              name: rootdisk
        terminationGracePeriodSeconds: 0
        volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: ${PVCNAME}
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
          name: cloudinitvolume

parameters:
- description: VM name
  from: 'fedora-[a-z0-9]{16}'
  generate: expression
  name: NAME
- name: PVCNAME
  description: Name of the PVC with the disk image
  required: true


